### PR TITLE
Add booking function and booking page

### PR DESCRIPTION
**Pull request by JulieYeeee**
Hi, Teacher Peng. Just finished booking function and booking page. 
Please do code review for me, thanks!

Name: 葉怡君

Links for testing :
Index page : http://54.225.122.244:3000/
Attraction page : http://54.225.122.244:3000/attraction/224
Booking page : http://54.225.122.244:3000/booking

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Comment by JulieYeeee** [comment]
Hi Teacher @cwpeng  
Feel so sorry and awkward for that I forgot to merge before committing and pushing week 6 code again.
The week 6 commit had been merged with main branch.

Here are records of the week 6 commit=>[ Link](https://github.com/JulieYeeee/taipei-day-trip-website/pull/7/commits/5e2e23d8f5b2f39992a75fd6d2f7b1334559441a)
Please do code review from this link.

Name: 葉怡君
Link for testing:
http://54.225.122.244:3000/

Thanks!

**Comment by cwpeng** [comment]
Not bad code with small issues:
1. `from xml.dom.expatbuilder import FragmentBuilderNS` is redundant.
2. Try to exclude `TapPay partner_key` and `DB password` in your public github repository.

**Comment by JulieYeeee** [comment]
Didn't notice the weird import, I will remove it. And also, I will do research and try to exclude the important data. Thanks for doing code review and giving me feedback.

**Pull request merged**
